.flake8, examples/technology_showcase/example_10_td_055_Rotor_Blade_Inverse_solve.py, examples/technology_showcase/readme.rst
Added new embedded gas turbine focused example on the inverse formulation on NASA 67 rotor fan blade model.
@koubaa @samigithub2022 Please review it and let me know. Thanks !
=> Added embed example on Rotor Blade Inverse solve

doc/source/conf.py
Fixing the doc html build issues caused by pyvista rcparam.
=> Pyvista rcparam documentation build fix

doc/source/index.rst
=> fix: index page

doc/source/_templates/README.md, doc/source/conf.py, doc/source/index.rst, examples/README.txt, examples/basic/topology_optimization_cantilever_beam.py, examples/basic/valve.py, examples/technology_showcase/Rotor_Blade_Inverse_solve.py
- modified alt text
- renamed file
- changed readme
=> Adding author information

doc/source/conf.py, examples/basic/topology_optimization_cantilever_beam.py, examples/basic/valve.py, examples/technology_showcase/Rotor_Blade_Inverse_solve.py
locally generated gifs ae now used directly rather than from _static folder
=> Update gif embedding

.pre-commit-config.yaml, examples/README.txt, examples/basic/contact_debonding.py, examples/basic/fracture_analysis_contact_debonding.py
=> Add Fracture analysis : contact debonding example

examples/basic/harmonic_acoustics.py, requirements/requirements_doc.txt
=> Add Harmonic Acoustics example

examples/technology_showcase/conact_wear_simulation.py
Example taken from remote/technology showcase
=> Adding contact wear simulation 

examples/basic/modal_acoustics.py, examples/basic/modal_acoustics_analysis.py
=> Add Modal acoustics example

.github/workflows/ci_cd_nightly.yml
Adds notify on failure  on teams.
Uses 242_candidate for nightly runs doc build only.
=> feat: Add nightly run for 242

.github/workflows/ci_cd.yml, .github/workflows/ci_cd_nightly.yml, requirements/requirements_doc.txt
update pymechanical and fix env
=> Fix : Env name 

.github/workflows/ci_cd_nightly.yml
=> Fix: version for nightly run

.github/dependabot.yml, .github/workflows/ci_cd.yml, .github/workflows/dependabot_automerge.yml, .gitignore, examples/README.txt
- Dependabot grouping
- Fix link
-  Add linkcheck
https://github.com/ansys/pymechanical-embedding-examples/actions/runs/8606423786/job/23584842784#step:9:64
link check status
=> Feat: Add linkcheck and dependabot grouping

.github/workflows/ci_cd_nightly.yml
=> Feat: show build info in nightly run

examples/technology_showcase/Rotor_Blade_Inverse_solve.py
Modified this technology showcase example with the thermal strain plot in the documentation. @dipinknair
=> added thermal strain plot instead of stress plot

examples/basic/topology_optimization_cantilever_beam.py
add code to choose the optimization type
=> Fix: topology optimization example

examples/basic/bolt_pretension.py, examples/basic/fracture_analysis_contact_debonding.py, examples/basic/harmonic_acoustics.py, examples/basic/modal_acoustics_analysis.py, examples/basic/readme.txt, examples/basic/steady_state_thermal_analysis.py, examples/basic/topology_optimization_cantilever_beam.py, examples/basic/valve.py, examples/technology_showcase/Rotor_Blade_Inverse_solve.py, examples/technology_showcase/conact_wear_simulation.py, examples/technology_showcase/non_linear_analsis_rubber_boot_seal.py
Update with new additions from pymechanical
Update APIs
=> Maint : Refactoring

.github/workflows/ci_cd.yml, .github/workflows/ci_cd_nightly.yml, requirements/requirements_doc.txt
=> FIX: Remove duplicates of python installation action

examples/02_technology_showcase/non_linear_analsis_rubber_boot_seal.py
=> FIX: Fix view for technology showcase example

.github/dependabot.yml, requirements/requirements_doc.txt
=> chore: Update dependencies

.github/workflows/ci_cd_nightly.yml, examples/00_tips/tips_01.py, examples/00_tips/tips_02.py, examples/00_tips/tips_03.py, examples/01_basic/bolt_pretension.py, examples/01_basic/fracture_analysis_contact_debonding.py, examples/01_basic/harmonic_acoustics.py, examples/01_basic/modal_acoustics_analysis.py, examples/01_basic/steady_state_thermal_analysis.py, examples/01_basic/topology_optimization_cantilever_beam.py, examples/01_basic/valve.py, examples/02_technology_showcase/Rotor_Blade_Inverse_solve.py, examples/02_technology_showcase/conact_wear_simulation.py, examples/02_technology_showcase/non_linear_analsis_rubber_boot_seal.py
Remove version number from the examples.
=> Maint: Remove version number

examples/01_basic/fracture_analysis_contact_debonding.py
Example fails in candidate because of new validation change in analysis setting
=> Fix:  Fracture analysis example

examples/00_tips/tips_01.py, examples/00_tips/tips_02.py, examples/00_tips/tips_03.py, examples/01_basic/bolt_pretension.py, examples/01_basic/fracture_analysis_contact_debonding.py, examples/01_basic/harmonic_acoustics.py, examples/01_basic/modal_acoustics_analysis.py, examples/01_basic/steady_state_thermal_analysis.py, examples/01_basic/topology_optimization_cantilever_beam.py, examples/01_basic/valve.py, examples/02_technology_showcase/Rotor_Blade_Inverse_solve.py, examples/02_technology_showcase/conact_wear_simulation.py, examples/02_technology_showcase/non_linear_analsis_rubber_boot_seal.py
=> Fix: Underline of the examples

examples/01_basic/fracture_analysis_contact_debonding.py
Reverting to original since the issue is fixed on product side
=> Revert "Fix:  Fracture analysis example"
